version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: torres-sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - torres-network
      - nginx-proxy-manager_default

  api:
    build: ./API
    container_name: torres-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=torres-sqlserver
      - DB_PORT=1433
      - DB_NAME=TP_CSID
      - DB_USER=sa
      - DB_PASSWORD=Password123!
    depends_on:
      - sqlserver
    networks:
      - torres-network
      - nginx-proxy-manager_default

  front:
    build: ./FRONT
    container_name: torres-front
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - torres-network
      - nginx-proxy-manager_default

networks:
  torres-network:
    driver: bridge
  nginx-proxy-manager_default:
    external: true

volumes:
  sqlserver-data: 