version: '3.8'

services:
  api:
    build: ./API
    container_name: torres-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - torres-network
      - nginx-proxy-manager_default

  front:
    build: ./FRONT
    container_name: torres-front
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - torres-network
      - nginx-proxy-manager_default

networks:
  torres-network:
    driver: bridge
  nginx-proxy-manager_default:
    external: true 