name: Frontend Deployment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: List directory structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Root directory contents:"
        ls -la /home/runner/work
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: |
        # Vérifier si le répertoire front existe
        if [ -d "front" ]; then
          cd front
          npm install
        elif [ -d "FRONT" ]; then
          cd FRONT
          npm install
        else
          echo "Le répertoire front ou FRONT n'existe pas"
          exit 1
        fi
    
    - name: Build
      run: |
        # Vérifier si le répertoire front existe
        if [ -d "front" ]; then
          cd front
          npm run build
        elif [ -d "FRONT" ]; then
          cd FRONT
          npm run build
        else
          echo "Le répertoire front ou FRONT n'existe pas"
          exit 1
        fi
    
    - name: Deploy to production server
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /path/to/your/app
          rm -rf front/build_old
          [ -d front/build ] && mv front/build front/build_old
          mkdir -p front/build
    
    - name: Copy build files
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "front/build/* || FRONT/build/*"
        target: "/path/to/your/app"
        strip_components: 1
        
    - name: Start frontend server
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /path/to/your/app/front
          pm2 delete front 2>/dev/null || true
          pm2 serve build 3000 --name front --spa 