name: Frontend Deployment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: List directory structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Searching for front directories:"
        find . -type d -name "front" -o -name "FRONT" | sort
        echo "Searching for package.json files:"
        find . -name "package.json" | sort
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: |
        # Rechercher le répertoire front avec un package.json
        FRONT_DIR=$(find . -type d -name "front" -o -name "FRONT" | sort | head -n 1)
        
        if [ -z "$FRONT_DIR" ]; then
          echo "Aucun répertoire front ou FRONT trouvé"
          exit 1
        fi
        
        echo "Utilisation du répertoire: $FRONT_DIR"
        
        if [ -f "$FRONT_DIR/package.json" ]; then
          cd "$FRONT_DIR"
          npm install
        else
          echo "Pas de package.json trouvé dans $FRONT_DIR"
          exit 1
        fi
    
    - name: Build
      env:
        CI: "false"  # Désactiver le traitement des avertissements comme erreurs
      run: |
        # Rechercher le répertoire front avec un package.json
        FRONT_DIR=$(find . -type d -name "front" -o -name "FRONT" | sort | head -n 1)
        
        if [ -z "$FRONT_DIR" ]; then
          echo "Aucun répertoire front ou FRONT trouvé"
          exit 1
        fi
        
        echo "Utilisation du répertoire: $FRONT_DIR"
        
        if [ -f "$FRONT_DIR/package.json" ]; then
          cd "$FRONT_DIR"
          npm run build
        else
          echo "Pas de package.json trouvé dans $FRONT_DIR"
          exit 1
        fi
    
    - name: Verify secrets
      run: |
        echo "Vérification des secrets..."
        if [ -z "${{ secrets.HOST }}" ]; then
          echo "❌ Le secret HOST n'est pas défini"
          exit 1
        else
          echo "✅ Le secret HOST est défini"
        fi
        
        if [ -z "${{ secrets.USERNAME }}" ]; then
          echo "❌ Le secret USERNAME n'est pas défini"
          exit 1
        else
          echo "✅ Le secret USERNAME est défini"
        fi
        
        if [ -z "${{ secrets.PASSWORD }}" ]; then
          echo "❌ Le secret PASSWORD n'est pas défini"
          exit 1
        else
          echo "✅ Le secret PASSWORD est défini"
        fi
        
        if [ -z "${{ secrets.PORT }}" ]; then
          echo "❌ Le secret PORT n'est pas défini"
          exit 1
        else
          echo "✅ Le secret PORT est défini"
        fi
        
        echo "Tous les secrets nécessaires sont définis"
    
    - name: Test SSH connection
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        timeout: 60s
        command_timeout: 60s
        script: |
          echo "SSH connection successful"
          echo "Current directory: $(pwd)"
          echo "Server information: $(uname -a)"
    
    - name: Prepare deployment directory
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        timeout: 60s
        command_timeout: 60s
        script: |
          echo "Préparation du répertoire de déploiement..."
          mkdir -p /path/to/your/app/front/build
          rm -rf /path/to/your/app/front/build_old
          if [ -d "/path/to/your/app/front/build" ]; then
            mv /path/to/your/app/front/build /path/to/your/app/front/build_old
          fi
          mkdir -p /path/to/your/app/front/build
    
    - name: Deploy frontend build
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        # Rechercher le répertoire front avec un package.json
        FRONT_DIR=$(find . -type d -name "front" -o -name "FRONT" | sort | head -n 1)
        BUILD_DIR="$FRONT_DIR/build"
        
        if [ ! -d "$BUILD_DIR" ]; then
          echo "Répertoire build non trouvé: $BUILD_DIR"
          exit 1
        fi
        
        echo "Répertoire build trouvé: $BUILD_DIR"
        echo "Contenu du répertoire build:"
        ls -la "$BUILD_DIR"
        
        # Créer un fichier tar pour le transfert
        tar -czf build.tar.gz -C "$BUILD_DIR" .
        
        # Utiliser sshpass pour le transfert
        echo "Transfert des fichiers vers le serveur..."
        sshpass -p "${{ secrets.PASSWORD }}" scp -o StrictHostKeyChecking=no -P ${{ secrets.PORT }} build.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/path/to/your/app/front/
        
        # Décompresser l'archive sur le serveur
        sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /path/to/your/app/front && tar -xzf build.tar.gz -C build && rm build.tar.gz"
    
    - name: Start frontend server
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        timeout: 60s
        command_timeout: 60s
        script: |
          cd /path/to/your/app/front
          pm2 delete front 2>/dev/null || true
          pm2 serve build 3000 --name front --spa 